### ISSUE TITLE
Too much logging

### ISSUE THREAD

**Issue by ericclemmons** [tomchentw/koa-webpack-dev#3]
Shouldn't logs be disabled by default?

> http://stackoverflow.com/questions/6807775/socket-io-remove-debug-mode

**Comment by tomchentw** [comment]
Yes my bad. @ericclemmons just curious, do you think this package is really helpful? Want your feedback :)

**Comment by ericclemmons** [comment]
@tomchentw I found it here:
> http://webpack.github.io/docs/dev-tools.html

Well, I _did_, until you asked, so now I'm wondering if I'm not supposed to be using it?

There's a competing project, but also not very up-to-date:
> https://github.com/mekwall/koa-webpack-dev-server

I just got everything working, but this is why I'm using it:

- Working on a large application that will need to bundle per-route and generate dynamic views.
- Want to be able to swap out the dev server for a webpack middleware for production use in the future.
- Need to add the dev server (and future middleware) to an existing Koa instance with existing routes.

So, that's my use-case, and why I've been getting this thing working tonight :)

Also, here's how I disabled logs (since `socket.io` is out-of-date):

```javascript
DevServer.hotModuleSocket(server, compiler).set('log', false);
```

**Comment by tomchentw** [comment]
@ericclemmons well, I agree. However, I found one solution which is more elegant and less "hacking".
The idea is simple: (we only talk about development mode)
1. Start you node.js server at port 3000
2. Start webpack-dev-server at port 8080
3. Then, at your nodes server, **proxy** request to the dev server
4. Also, proxy the web socket request.

The gist would be like this. https://gist.github.com/tomchentw/7aaeb427703c4d15705d
I think I'll write a blog post for this, but it really worth you to take a look at it. :)

**Comment by ericclemmons** [comment]
I started with something similar, but that solution ultimately doesn't match what I'll be launching with: webpack compilation as a middleware within the same server instance.

My preference is to solve this part of the compilation (with debug tools, such as HMR) so that the production middleware is a stripped down version.

Am I doing something others aren't?

**Comment by tomchentw** [comment]
Yeah, I'll suggest don't mix your compilation logic into your server,
though it's temptating to do so.

What I'll do is I'll do a precipice step before deploying my server, so the
user will get the complied assets immediately. Also we can use Nginx to
serve instead of using static middleware, which boosts performance.

**Comment by ericclemmons** [comment]
I believe this is actually useful behavior, seeing how our app is coming from Symfony2 with Assetic:
> http://symfony.com/doc/current/cookbook/assetic/asset_management.html

I'll evaluate if this is even possible, but I'm not exactly eager to do what I did with Angular and ship tons of CSS/JS in single files.  It killed our mobile users =/

**Comment by tomchentw** [comment]
With wepback, you have auto splitting of modules into chunks.
